# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spike.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bspike.proto\x12\rsynapse.spike\"@\n\x0cSpikeRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\nmax_tokens\x18\x02 \x01(\r\x12\x0c\n\x04seed\x18\x03 \x01(\r\"l\n\rSpikeResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x18\n\x10tokens_generated\x18\x02 \x01(\r\x12\x12\n\nelapsed_ms\x18\x03 \x01(\x03\x12\x10\n\x08\x66inished\x18\x04 \x01(\x08\x12\r\n\x05\x65rror\x18\x05 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spike_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SPIKEREQUEST._serialized_start=30
  _SPIKEREQUEST._serialized_end=94
  _SPIKERESPONSE._serialized_start=96
  _SPIKERESPONSE._serialized_end=204
# @@protoc_insertion_point(module_scope)
